# Generated by Django 2.2 on 2022-10-17 07:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_creditcard_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='web3_wallet',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='web3_wallet',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
