# Generated by Django 2.2 on 2022-10-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20221017_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='wallet_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
