# Generated by Django 2.2 on 2022-10-20 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20221019_1004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Language',
            new_name='Languages',
        ),
    ]
