# Generated by Django 2.2 on 2022-10-20 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20221020_0434'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='languages',
            table='language',
        ),
    ]
