# Generated by Django 2.2 on 2022-11-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20221102_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluploadmedia',
            name='media_file_name',
        ),
        migrations.RemoveField(
            model_name='historicaluploadmedia',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='uploadmedia',
            name='media_file_name',
        ),
        migrations.RemoveField(
            model_name='uploadmedia',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='historicaluploadmedia',
            name='media_file',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadmedia',
            name='media_file',
            field=models.ImageField(blank=True, null=True, upload_to='upload-media/'),
        ),
    ]
