# Generated by Django 2.2 on 2022-10-20 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20221020_0535'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='languages',
            table='api_language',
        ),
    ]
