# Generated by Django 2.2 on 2022-10-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20221020_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='discount_from_users',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
