# Generated by Django 2.2 on 2022-10-20 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_userpreferences_discount_from_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookmarks',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
