# Generated by Django 2.2 on 2022-10-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_userbankaccounts'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userbankaccounts',
            index=models.Index(fields=['id'], name='user_bankac_id_477c64_idx'),
        ),
        migrations.AlterModelTable(
            name='userbankaccounts',
            table='user_bankaccounts',
        ),
    ]
