# Generated by Django 2.2 on 2022-10-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_ticketcategories_usertickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertickets',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='upload-media/'),
        ),
    ]
