# Generated by Django 2.2 on 2022-10-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_usertickets_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertickets',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
    ]
