# Generated by Django 2.2 on 2022-10-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20221021_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertickets',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertickets',
            name='open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertickets',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
