# Generated by Django 2.2 on 2022-10-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20221026_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertickets',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
