# Generated by Django 2.2 on 2022-12-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20221229_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='wallet_privatekey',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_privatekey',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
