# Generated by Django 2.2 on 2023-01-02 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20221230_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='wallet_token',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='web3_wallet',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wallet_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='web3_wallet',
        ),
    ]
