# Generated by Django 2.2 on 2023-01-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20230102_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='wallet_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
