# Generated by Django 2.2 on 2023-03-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_auto_20230303_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='wallet_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wallet_address',
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='referred_by_wallet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by_wallet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
