# Generated by Django 2.2 on 2023-03-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_auto_20230314_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='wallet_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
