# Generated by Django 2.2 on 2023-03-15 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_auto_20230307_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payouts',
            options={'verbose_name_plural': 'Payouts'},
        ),
    ]
