# Generated by Django 2.2 on 2023-03-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_auto_20230315_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='referred_by_wallet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by_wallet',
            field=models.TextField(blank=True, null=True),
        )
    ]
