# Generated by Django 2.2 on 2023-04-24 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_auto_20230320_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTickets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('authId', models.CharField(blank=True, max_length=200, null=True)),
                ('eventId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Events')),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserTickets',
            },
        ),
    ]
