# Generated by Django 2.2 on 2023-03-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_auto_20230314_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payouts',
            options={'verbose_name': 'Payout'},
        ),
        migrations.AddField(
            model_name='historicalmessages',
            name='media_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalmessages',
            name='msg_media',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='media_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='msg_media',
            field=models.URLField(blank=True, null=True),
        ),
    ]
