# Generated by Django 2.2 on 2023-03-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_auto_20230316_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='referred_by_wallet',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referred_by_wallet',
        ),
    ]
