# Generated by Django 2.2 on 2023-03-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_auto_20230316_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmessages',
            name='msg_media',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalmessages',
            name='msg_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='msg_media',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='msg_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
